[package]
name = "robopoker-core"
version = "0.1.0"
edition = "2021"
license = "MIT"

[features]
default = ["std"]
std = []
shortdeck = []
proptest = ["dep:proptest"]

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
proptest = "1.5"

[dependencies.proptest]
version = "1.5"
optional = true
